name: "Coverage Testing"
on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Coverage Testing"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1
      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: "Install Dependencies"
        run: yarn install
      - name: "Compile the Contracts"
        run: yarn build
      - name: "Run the Tests"
        run: yarn test
      - name: "Run Cover"
        run: yarn coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
